I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 90, in script
    chet.c "testing"
Exception: Sayer 'chet.c' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 90, in script
    chet.c "testing"
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'chet.c' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Orbital Weapons Dating Simulator 1.0
Mon May  8 22:30:40 2023
